# This is a basic workflow to help you get started with Vue s3 deployer action

name: Deployment PROD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/cicd